[project]
name = "protfolio"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
license = "XAGv1"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.5",
]
